# Generated by Django 4.2.3 on 2023-09-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllDist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BankForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Age', models.DecimalField(decimal_places=3, max_digits=3)),
                ('Phone', models.IntegerField()),
                ('Address', models.TextField(max_length=250)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Credit_card', models.CharField(max_length=20)),
                ('Materials', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.alldist')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ('name',),
            },
        ),
    ]
